
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Not the strict env() helper: that throws at config-load time if unset,
    // which breaks `prisma generate` in CI where no real DATABASE_URL exists.
    // Commands that actually connect (migrate deploy, db seed) still get the
    // real value from .env via dotenv/config above.
    url: process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
